### ISSUE TITLE
数据集下载失败的问题

### ISSUE THREAD

**Issue by ByskyXie** [JasonYanxx/STNN#2]
作者你好，请问数据集的IP 106.12.19.243是校内IP吗？
我用教育网下载不了。如果能发我一份就更好了（byskyXie@qq.com），感谢 :)

**Comment by ByskyXie** [comment]
哈哈，看到网盘了，还以为是两个文件。感谢感谢

**Comment by zhongy1999** [comment]
这个数据集还是下载不了欸，请问也可以发一份到我的邮箱吗2356920697@qq.com，非常感谢了。

**Comment by bugerror404** [comment]
请问代码跑通了吗？我的有错误，方便的话可以请教一下吗，我的邮箱是lichunye0222@163.com。感谢感谢

**Comment by ByskyXie** [comment]
> 请问代码跑通了吗？我的有错误，方便的话可以请教一下吗，我的邮箱是[lichunye0222@163.com](mailto:lichunye0222@163.com)。感谢感谢

没，我主要是拿了数据集。这个数据集时间是连续的，可以拼成一个3023x192x192的长序列，采样率大概25.89%。

**Comment by bugerror404** [comment]
好的，请问一下，你的也是交通流预测模型吗

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年02月27日 10:18 |
| 收件人 | JasonYanxx/STNN ***@***.***> |
| 抄送人 | bugerror404 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [JasonYanxx/STNN] 数据集下载失败的问题 (Issue #2) |

***@***.***。感谢感谢

没，我主要是拿了数据集。这个数据集时间是连续的，可以拼成一个3023x192x192的长序列，采样率大概25.89%。
